# Generated by Django 5.0.6 on 2025-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Books', 'Books'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
